AllCops:
  Exclude:
    - "spec/dummy/**/*"
    - "vendor/bundle/**/*"
  NewCops: enable

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/simple_scheduler/task_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
